### PR TITLE
Bubblemenu

### PR DESCRIPTION
**Pull request by rowheat02**
Bubble menu added.

Three buttons are added to make the selected text bold, italic, and strike.

Screenshot 2023-06-18 at 23 41 23

### CODE REVIEW

**Comment by steven-tey** [comment]
This is fantastic, but ideally we'd want to add more features to the bubble menu + make it look nicer UI-wise before rolling it out.

Take something like Notion's bubble menu for reference: 

CleanShot 2023-06-18 at 13 43 53

**Comment by redac** [comment]
Currently working on this — @steven-tey does moving into a separate component sound good to you?

**Comment by sereneinserenade** [comment]
I've made a PR https://github.com/steven-tey/novel/pull/14

**Comment by rowheat02** [comment]
I'm closing the PR because many things have already been done in #14

**Pull request closed without merging**
