### PR TITLE
Fix: #145

### LINKED ISSUE #145: Image placeholder implementation breaks when drag & dropped after a node
Screen recording to show the issue in action:

https://github.com/steven-tey/novel/assets/28986134/0c0d4c3e-4486-4505-aeaa-8eb7dab50fa2

### PR DESCRIPTION
**Pull request by prathameshjchavan**
Fixes #145 
Bug: Image placeholder implementation breaks when drag & dropped after a node

Solution:
1. In upload-image.tsx
* Placeholder was being added to the wrong position
* Adding the placeholder at 'pos' position instead of 'pos+1' position fixes the issue
2. In props.ts
* When getting the 'coordinates.pos' position value as 0, it was regarded as falsy
* Checking if it is getting a number else '0 - 1' is returned

https://github.com/steven-tey/novel/assets/74180320/bf094f2d-d2f5-41cb-a586-c917cf2fccfd

### CODE REVIEW

**Comment by prathameshjchavan** [comment]
@steven-tey Please have a look and let me know

**Comment by steven-tey** [comment]
This is brilliant! Thank you for the fix 🙏

Side note: good catch of the 0 === falsy → that always trips me up 😅

**Comment by steven-tey** [comment]
Just found an edge case that breaks: when you upload an image inline, the placeholder text gets overlayed by the placeholder image:

https://github.com/steven-tey/novel/assets/28986134/574aa353-b993-4a96-8e4b-3ae089852b56

**Comment by andrewdoro** [comment]
closed this one, I need to rethink the image upload flow. (it is proned to a lot of bugs like this)

**Pull request closed without merging**
