### PR TITLE
add event listeners to prevent ai writing all over the place on click

### PR DESCRIPTION
**Pull request by GraemeFulton**
Problem:
When the AI starts streaming, and the user clicks somewhere, the cursor position changes, and the AI continues writing wherever the user clicks. See the video:

▶️ https://www.loom.com/share/178b6e5e4bba476fb812cd7338b48f75?sid=20be9f82-2361-48a0-9600-cc6523db4506

Solution:
An event handler that prevents user cilcking with a simple confirm alert. This behaviour is the same as how Notion prevent user interaction whilst AI is writing.

---
Maybe this PR isn't necessary as it's based on preference I think. But it might be useful for others to see!

### CODE REVIEW

**Comment by steven-tey** [comment]
This is brilliant! It's the same UX as Notion's I believe, which makes sense: 

CleanShot 2023-06-19 at 08 34 56

We'd also want to account for "Enter" keyboard event and trigger this confirm alert as well!

**Comment by GraemeFulton** [comment]
Yeah I was initially trying to reset the position of the cursor each time a text stream came in, but saw Notion did it this way..which is much easier!

In my app though, I have the `useCompletion` hook at the top editor level, so I can show a real modal instead of the alert.

Some confusion I had with the vercel `useCompletion` hook was that it was used in 2 places in novel:
1. at the top level editor
2. within suggestion plugin

I found it confusing that you can access the `completion` helper of `useCompletion` at the top level to retrieve and insert the text..but the callbacks such as `onResponse` can't be accessed at the top level - it only runs from where you call `complete()` (in this case, in the suggestion plugin)

For that reason, in my app, I run the hook at the top level, and I'm passing all the results of the hook down to the plugin. Then I can show a real modal over the editor instead of using this confirm alert

**Comment by steven-tey** [comment]
@GraemeFulton re this:

> but the callbacks such as onResponse can't be accessed at the top level 

That's a great point, I just confirmed with @shuding that it's the SWR behavior, and that’s really an argument between callback-APIs and hook-APIs. E.g. if you are showing a toast after `onFinish`, you certainly don’t want it to come up in multiple places but only the instance that you called `complete`.

**Comment by steven-tey** [comment]
Gonna merge this for now! Thank you again for the PR!

I ended up handling the `stop` event from parent Editor component – this doesn't work for slash commands right now since it's a different component but it's actually a bug in `ai` and we'll be fixing it soon!

**Comment by GraemeFulton** [comment]
awesome, thanks Steven! that's a great improvement having access to `stop()`, and makes more sense along with the keydown handler - thanks for improving it!

**Pull request merged**
