### PR TITLE
Preserve paragraph integrity in generated text

### PR DESCRIPTION
**Pull request by jt6677**
This commit parses the generated text into paragraph nodes to preserve the 
original paragraph structure OnFinish. Previously, the text was being trimmed into a 
single paragraph upon any edits due to the use of '\n\n' for paragraph separation. 
With this change, each paragraph maintains its integrity even after edits.

### CODE REVIEW

**Comment by steven-tey** [comment]
Hmmm just checked this out – it doesn't work unfortunately:

CleanShot 2023-07-07 at 16 58 15

**Comment by jt6677** [comment]
The code is trying to solve this problem.   The code is parsing streamed text into "paragraph text type".  It does not know the original numberlist type .
(original)
https://github.com/steven-tey/novel/assets/62420169/8c548607-6ee0-499f-ac22-4e52fa801b6f
(added parsing into paragraphs using"/n/n")
https://github.com/steven-tey/novel/assets/62420169/2cfbd1c5-1686-4b99-94d3-9350284b42b6

**Comment by steven-tey** [comment]
@jt6677 ohhhh gotcha! I will need to think this one through a bit more 🙏

**Comment by andrewdoro** [comment]
I'll close this PR because of the recent changed and AI example here #297. For direct streaming we might have a new example

**Pull request closed without merging**
