### PR TITLE
Added To-do List option in editor just like notion

### PR DESCRIPTION
**Pull request by umeshjain1999**
Here is the preview of how it looks

novel

This might become my first contribution. Let me know If I can improve anything.

Thanks!

### CODE REVIEW

**Comment by steven-tey** [comment]
@umeshjain1999 This is awesome!! I added a simple line through + greyed out text when a TODO item is checked off (similar to Notion's)

https://github.com/steven-tey/novel/assets/28986134/3e833032-02c4-49f5-b85a-b315ec5a9a3f

Was wondering if it's possible to add a custom CSS animation of the tick, e.g. something like this: https://codepen.io/abottega/pen/vNzQMo

**Comment by umeshjain1999** [comment]
Oh Nice ✨ I will also check If I can do that custom animation on tick.

**Comment by steven-tey** [comment]
Also, what's your Twitter handle @umeshjain1999? Would love to give you a shoutout on Twitter when this is done!

**Comment by umeshjain1999** [comment]
here “pinktshurt” 🙌🏽

**Comment by steven-tey** [comment]
OK I think I got it @umeshjain1999 

https://github.com/steven-tey/novel/assets/28986134/dec62b36-7bde-418a-9e74-b020181c9a46

**Comment by umeshjain1999** [comment]
looks unique!

**Pull request merged**
