### PR TITLE
Fix/collision detection for selector dropdowns

### PR DESCRIPTION
**Pull request by prathameshjchavan**
Fixes Collision detection for Selector dropdowns #64

- Added Radix Popover for Color Selector
- Added fixed height for color selector and overflow scroll
- Fixed interactive issue after implementing Radix Popover

https://github.com/steven-tey/novel/assets/74180320/cb45fec4-672d-4edc-aaab-795befe8c698

### CODE REVIEW

**Comment by steven-tey** [comment]
Incredible! Wanna add this to the `NodeSelector` as well? 🙏

**Comment by prathameshjchavan** [comment]
> Incredible! Wanna add this to the `NodeSelector` as well? 🙏

I think the node selector is already perfect. Please let me know if I missed out something.


https://github.com/steven-tey/novel/assets/74180320/9a620087-8627-44de-803e-20ef503ded9e

**Comment by steven-tey** [comment]
Converting the `NodeSelector` to Radix Popover would be great because it currently doesn't handle collision detection well 😅 

CleanShot 2023-08-25 at 00 07 23@2x

**Comment by steven-tey** [comment]
Added this to `NodeSelector` – merging now! Thank you!

**Pull request merged**
