### PR TITLE
Improve Image Uploading Experience

### PR DESCRIPTION
**Pull request by hernancito**
Shows the base64 version of the image as a preview while the upload is in progress, and when it's done, replaces the base64 URL with the uploaded URL #36

### CODE REVIEW

**Comment by steven-tey** [comment]
@hernancito incredible work! Planning to take a look at this over the weekend!

P.S.: Huge fan of Aerolab btw – I visited the HQ in Buenos Aires and worked from there a couple of times! Really love the vibes & culture 😁

**Comment by steven-tey** [comment]
Incredible work @hernancito!! 👏 

I'm trying this out now and it looks like the image is getting uploaded at the location of the cursor – and not at the location of the image drop:

https://github.com/steven-tey/novel/assets/28986134/1f3de3ef-6bed-46b0-b5f1-bab27c1edbd2

**Comment by steven-tey** [comment]
I fixed it by adding a 3rd prop to `startImageUpload`: `pos` that's the position where the image should be inserted <picture data-single-emoji=":cele-cry:" title=":cele-cry:">:cele-cry:</picture>

**Comment by steven-tey** [comment]
Just realized this doesn't handle invalid file types either:

CleanShot 2023-07-07 at 23 10 43

Will think about it!

**Comment by steven-tey** [comment]
Incredible work on this @hernancito 👏 thank you so much for the PR!

Will be announcing this on Twitter tomorrow – stay tuned!

**Comment by hernancito** [comment]
Nice catch @steven-tey I didn't test it dropping pictures, my bad. Thank you for the improvements

**Comment by lumpinif** [comment]
hey guys, thank you for your amazing works.
 
quick question: How can we handle removing the placeholder image when there is an error on uploading the image to the DB? I have tried various ways, but it seems a little bit tricky to me. The only way to remove the placeholder image now is to refresh which is kind of bad user experience.

**Comment by hernancito** [comment]
Hi @lumpinif! I submitted a PR https://github.com/steven-tey/novel/pull/390 to address this scenario. The key is to remove the image placeholder when the promised is rejected.

**Comment by lumpinif** [comment]
> Hi @lumpinif! I submitted a PR #390 to address this scenario. The key is to remove the image placeholder when the promised is rejected.

Nice work!
Appreciate it very much

Also, do we have a solution for something like onDeleteImage? Because we currently only have a plugin to upload images and get an image-upload function for uploading an image to the backend, however, I was trying to remove the image both from the client side and the backend side for database scaleable and billing reasons. But I found that is quite difficult for me to make that happen

**Comment by hernancito** [comment]
In that case, you'll need to keep track of the data in your editor. Although deleting an image from the backend is not a great solution as a user can undo the deletion and the image (already cached in the browser) will be displayed in the editor but will not be saved in the database.

**Comment by lumpinif** [comment]
> In that case, you'll need to keep track of the data in your editor. Although deleting an image from the backend is not a great solution as a user can undo the deletion and the image (already cached in the browser) will be displayed in the editor but will not be saved in the database.

fair point! thank you @hernancito

**Comment by lumpinif** [comment]
> In that case, you'll need to keep track of the data in your editor. Although deleting an image from the backend is not a great solution as a user can undo the deletion and the image (already cached in the browser) will be displayed in the editor but will not be saved in the database.

just checked the PR https://github.com/steven-tey/novel/pull/390 still not merged, can't wait 👍

**Comment by andrewdoro** [comment]
hey just merged the PR, thank your for your work @hernancito

**Pull request merged**
