### PR TITLE
feat: add image resizer

### PR DESCRIPTION
**Pull request by vincent0426**
feat for #92 :)

### CODE REVIEW

**Comment by steven-tey** [comment]
This is awesome! Since the resizing keeps the same aspect ratio, can we limit the draggable cursors to just the left and right sides? Having 8 draggable points is a bit confusing

CleanShot 2023-07-13 at 19 05 49

Notion's as inspo:

CleanShot 2023-07-13 at 19 08 20

**Comment by vincent0426** [comment]
Hi @steven-tey. Yes. I fix that!

**Comment by steven-tey** [comment]
One last thing – it's a bit odd that when you resize the image, the blue selection borders disappears `onKeyUp`:

https://github.com/steven-tey/novel/assets/28986134/f360d17a-18a9-449d-96af-55ecd983d266

Would it be possible to keep them and only deselect if the user clicks elsewhere?

**Comment by vincent0426** [comment]
@steven-tey Added! Please review and let me know if there are any issues.

**Pull request merged**
