### PR TITLE
feat: added custom scroll bar style

### PR DESCRIPTION
**Pull request by varun2948**
Added Custom Styling on Scrollbar to make it look nice rather than native scrollbar
image

### CODE REVIEW

**Comment by steven-tey** [comment]
Appreciate the PR @varun2948 but not sure if we want to deviate from browser native scrollbar styles 😅

For reference, Notion's editor uses browser native scrollbar styles as well:

CleanShot 2023-06-24 at 10 45 02

**Comment by varun2948** [comment]
@steven-tey thanks for the feedback as my system is Linux and the browser is Chrome my scrollbar natively looks like this 
image

that's why I thought of changing the scrollbar from native to something nice looking but I noticed that for all the MAC users it looks similar to what I added  :laughing: so I guess this PR doesn't really do much so I will close this PR for now 
Thanks @steven-tey I will look into some other feature to work on and contribute :smile:

**Comment by steven-tey** [comment]
Reopening this as I just saw how the scrollbar looks on windows via this comment: https://github.com/steven-tey/novel/pull/62#issuecomment-1614597548

If we can make the scrollbar styles as similar as possible to the Mac native styles (lighter shade of the thumb, transparent background) – then we can merge this and make sure the scrollbar is consistent across devices 😄 

Sorry again for closing this prematurely! 🙏

**Comment by varun2948** [comment]
no worries @steven-tey,  i will fix it and raise a PR.

**Comment by steven-tey** [comment]
@varun2948 let's continue it from this PR + make sure it works with dark mode too (#38)

**Comment by varun2948** [comment]
@steven-tey does this look fine for you? i have somewhat adjusted the width and the shades

https://github.com/steven-tey/novel/assets/37866666/c2af5796-ba89-45e9-9203-d1c076ac5119

**Comment by steven-tey** [comment]
Hmmm this is still not cutting it, I'm sorry 😅 

Native Mac scrollbar styles:
CleanShot 2023-07-04 at 15 05 50

Custom scrollbar styles in this PR:
CleanShot 2023-07-04 at 15 05 32

As you can see the positioning of the custom scrollbar is offsetting the div's contents, which is not the case in the Mac native styles

**Comment by steven-tey** [comment]
Closing this for now but we can revisit this in the future! Thank you!

**Pull request closed without merging**
