### PR TITLE
Disable local storage option

### PR DESCRIPTION
**Pull request by krehak**
Fixes issue #137

### CODE REVIEW

**Comment by SimplyMerlin** [comment]
this needs to be merged asap, this package is unusable without this. It's even broken in [vercel/platforms](https://github.com/vercel/platforms)!

**Review by calebfrieze — APPROVED** [review]

**Comment by Elon-Mask12** [comment]
Agreed!
I have this use case where upon clicking a button i wanna add some text to the editor.
Replacing localstorage with useState seems to be the only fix imo.

**Comment by Michota** [comment]
Why its still not merged? How can i apply this if i want to use `npm i novel`?

**Comment by krehak** [comment]
> Why its still not merged? How can i apply this if i want to use `npm i novel`?

probably the only way to achieve that would be by using one of the "hacks", such as https://github.com/steven-tey/novel/issues/137#issuecomment-1728353624

**Comment by Michota** [comment]
No, i managed to do it the way it was shown in the commit i linked. Why
wont u merge this?

Dawid Michota

wt., 26 wrz 2023, 16:37 użytkownik Patrik Krehák ***@***.***>
napisał:

**Comment by Michota** [comment]
> > Why its still not merged? How can i apply this if i want to use `npm i novel`?
> 
> probably the only way to achieve that would be by using one of the "hacks", such as [#137 (comment)](https://github.com/steven-tey/novel/issues/137#issuecomment-1728353624)

I edited package and used patch-package. It works thanks to commit you pulled @krehak. Many thanks!

**Comment by krehak** [comment]
> > > Why its still not merged? How can i apply this if i want to use `npm i novel`?
> > 
> > 
> > probably the only way to achieve that would be by using one of the "hacks", such as [#137 (comment)](https://github.com/steven-tey/novel/issues/137#issuecomment-1728353624)
> 
> I edited package and used patch-package. It works thanks to commit you pulled @krehak. Many thanks!

You are welcome :)

**Comment by steven-tey** [comment]
Apologies for the delay here – merging this PR now! 

`novel@0.1.21` now has a `disableLocalStorage` prop that allows you to disable reading / writing content from local storage!

Thank you again @krehak for the fix + the patch as well to get folks through the last 2 weeks 😅 🙏

**Pull request merged**
