### PR TITLE
add drag and drop tiptap extension

### PR DESCRIPTION
**Pull request by MomenSherif**
# Loom
https://www.loom.com/share/d03606a9a2454e4e9a0dba0c60880615?sid=2c2ba4a5-6daf-401c-b37c-9bf107f44340

Found this cool https://github.com/pierre-lgb/slashwriter, which implements [tiptap's experimental global drag handler](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Experiments/GlobalDragHandle/Vue/DragHandle.js)
added it as an extension to Novel

### CODE REVIEW

**Comment by MomenSherif** [comment]
@steven-tey

**Comment by steven-tey** [comment]
@MomenSherif love this! Since we recently migrated to a monorepo structure, can you please refactor this PR to resolve the merge conflicts? Here are some instructions: https://github.com/steven-tey/novel#setting-up-locally

**Comment by MomenSherif** [comment]
Sure will do that

**Comment by MomenSherif** [comment]
@steven-tey new PR https://github.com/steven-tey/novel/pull/126

**Pull request closed without merging**
