### PR TITLE
fix: leaking css affecting buttons outside of the package

### PR DESCRIPTION
**Pull request by MarkLyck**
Delete tailwind.css from the npm package.

fixes:

#143
#135

### CODE REVIEW

**Comment by jaqnjilai** [comment]
fyi, i downgraded to 0.1.17 for now to fix this issue

**Comment by steven-tey** [comment]
This breaks all the styles for the editor:

CleanShot 2023-09-09 at 10 22 31

**Comment by MarkLyck** [comment]
@steven-tey doesn't it only break if the application the package is used in, doesn't already have tailwind styles setup?

For me when I import this package, I get 2 sets of tailwind.css styles, one for my application level tailwind, and one from this package that's leaking and overwriting my other CSS, such as making buttons transparent.

**Comment by jonschlinkert** [comment]
Having the same issue. This broke styles across our app globally, not just where the component is used.

**Comment by steven-tey** [comment]
This will be fixed when we cut a new version for #161 – shoutout to @eyalcohen4 for the fix!

**Pull request closed without merging**
